---
# Installs Riak

- name: Ensure repository key for packagecloud.io is in place
  apt_key: url=https://packagecloud.io/gpg.key id=D59097AB state=present

- name: Add packagecloud.io repository
  apt_repository: repo="deb https://packagecloud.io/basho/riak/ubuntu/ trusty main"
                  state=present
                  update_cache=yes

- name: Install Riak
  apt: pkg=riak state=present update_cache=yes cache_valid_time=3600

- name: Copy riak.conf into place
  copy: src=etc_riak_riak.conf
        dest=/etc/riak/riak.conf
        owner=riak
        group=riak

- name: mount the riak volume with optimized settings
  mount: name={{ riak_mountpoint }}
         src={{ riak_partition }}
         opts="{{ riak_mount_options }}"
         fstype="{{ riak_filesystem }}"
         state=mounted

- name: create script with disk tuning commands
  template: src=usr_local_bin_riak_disk_tune.sh.j2
            dest=/usr/local/bin/riak_disk_tune.sh
            owner=root
            group=root
            mode=0750

- name: Add cron entry to tune disks upon startup
  cron: name="riak disk tune"
        special_time="reboot"
        job="/usr/local/bin/riak_disk_tune.sh"

- name: Create /etc/default/riak
  copy: content="ulimit -n 65536"
        dest=/etc/default/riak
        owner=root
        group=root
        mode=0644

- name: Update open file limits for Riak
  copy: src=etc_security_limits.d_riak.conf
        dest=/etc/security/limits.d/riak.conf
        owner=root
        group=root
        mode=0644

- name: Optimize Riak sysctl settings
  template: src=etc_sysctl.d_30-riak.conf.j2
            dest=/etc/sysctl.d/30-riak.conf
            owner=root
            group=root
            mode=0644

- name: Configuration CloudWatch logs
  copy: src=var_awslogs_etc_config_riak.conf
        dest=/var/awslogs/etc/config/riak.conf
        owner=root
        group=root
        mode=0644

- name: Install the Riak startup script
  copy: src=usr_local_bin_riak_startup.sh
        dest=/usr/local/bin/riak_startup.sh
        owner=root
        group=root
        mode=0750

- name: Configuration Riak startup script to run upon startup
  cron: name="riak startup"
        job="/usr/local/bin/riak_startup.sh"
        special_time="reboot"
        state=present

- name: Ensure Riak is enabled
  service: name=riak state=stopped enabled=yes
