---
# Enables enhanced networking
# https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html

- name: Install dkms
  apt: name=dkms state=present

- name: Download and extract ixgbevf
  unarchive: src=http://downloadmirror.intel.com/18700/eng/ixgbevf-3.1.2.tar.gz
             dest=/usr/src
             creates=/usr/src/ixgbevf-3.1.2
             copy=no

- name: Copy dkms file
  copy: src=usr_src_ixgbevf-3.1.2_dkms.conf
        dest=/usr/src/ixgbevf-3.1.2/dkms.conf

- name: Add ixgbevf module
  command: "dkms add -m ixgbevf -v 3.1.2"
  changed_when: '"DKMS tree already contains" not in ixgbevf_module.stderr'
  register: ixgbevf_module
  failed_when: false

- name: Build ixgbevf module
  command: "dkms build -m ixgbevf -v 3.1.2"
  when: ixgbevf_module.changed

- name: Install ixgbevf module
  command: "dkms install -m ixgbevf -v 3.1.2"
  when: ixgbevf_module.changed

- name: Rebuild initramfs
  command: "update-initramfs -c -k all"
  when: ixgbevf_module.changed
